project:
  type: website
  render: 
    - setup.md
    - "Workshops/*"

website:
  title: "Python Training Intensive"
  sidebar:
    contents:
      - href: setup.md
        text: Home
      - auto: "Workshops"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto