project:
  type: website
  render: 
    - setup.md
    - "Workshops/*"
    - "WIPs/*"
    - "Projects/*"

website:
  title: "Python Training Intensive"
  navbar:
    search: true
    left:
      - text: "Workshops"
        href: Workshops/index.qmd
      - text: "Project Gallery"
        href: Projects/project_gallery.qmd
  sidebar: 
    contents:
      - setup.md
      - auto: "Workshops"
      - section: The Project
        contents:
        - auto: "Projects/*"


## Hybrid nav - probably not worth it
#  navbar:
#    search: true
#    left:
#      - text: "Workshops"
#        href: Workshops/Workshops.md
#      - text: "Project"
#        href: Project/project.md

#  sidebar:
#    - title: "Workshops"
#      contents:
#        - href: setup.md
#          text: Setup
#        - auto: "Workshops"

#    - title: "Project"
#      contents:
#        - auto: "Project"

format:
  html:
    theme: 
      - default
      - custom.scss

    toc: true