project:
  type: website
  render: 
    - setup.md
    - "Workshops/*"

website:
  title: "Python Training Intensive"
  navbar:
    background: primary
    foreground: light
    search: true

  sidebar:
    contents:
      - href: setup.md
        text: Home
      - auto: "Workshops"

format:
  html:
    theme: 
      - default
      - custom.scss

    toc: true

execute:
  freeze: auto