project:
  type: website
  render: 
    - setup.md
    - "Workshops/*"
    - "Projects/*"
    - project_gallery.qmd

website:
  title: "Python Training Intensive"
  navbar:
    search: true
    left:
      - text: "Workshops"
        href: Workshops/index.qmd
      - text: "Project Gallery"
        href: project_gallery.qmd
      - text: "UQ Library Technology Training"
        href: https://uqlibrary.github.io/technology-training
  sidebar: 
    - title: "Workshops"
      collapse-level: 1
      contents:
        - setup.md
        - auto: "Workshops"
        - section: The Project
          contents:
          - auto: "Projects/*"
    


format:
  html:
    theme: 
      - default
      - custom.scss
    toc: true
    embed-resources: false